# Generated by Django 6.1.1 on 2026-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Data Analytics', 'Data Analytics'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
